/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import Logica.SocialClass;
import Logica.UberSocial;
import static Swing.Log_In.userLogin;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class comment extends javax.swing.JFrame {
    UberSocial Social;
    ArrayList<String> usuarios =new ArrayList();;
    ArrayList<String> post =new ArrayList();
    /**
     * Creates new form comment
     */
    public comment(UberSocial Social) {
        initComponents();
        this.Social=Social;
        setUsers();
    }
    public Object user;
    public int id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Posts = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        Usuarios = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Posts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eliga el usuario" }));
        Posts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PostsItemStateChanged(evt);
            }
        });
        Posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostsActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Comentario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(usuarios.toArray()));
        Usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UsuariosItemStateChanged(evt);
            }
        });
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Posts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String commentCrear=JOptionPane.showInputDialog("Comentario: ");
            user=Usuarios.getSelectedItem();
            id=Posts.getSelectedIndex();
            Social.agregarComment(userLogin, id, user.toString(), commentCrear);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PostsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PostsItemStateChanged
        // TODO add your handling code here:
        id=Posts.getSelectedIndex();
    }//GEN-LAST:event_PostsItemStateChanged

    private void UsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UsuariosItemStateChanged
        // TODO add your handling code here:
        user=Usuarios.getSelectedItem();
        post.clear();

    }//GEN-LAST:event_UsuariosItemStateChanged

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        setPosts();
        Posts.setModel(new javax.swing.DefaultComboBoxModel<>(post.toArray()));
    }//GEN-LAST:event_UsuariosActionPerformed

    private void PostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Post(Social).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setUsers(){
        usuarios.clear();
        for (SocialClass Cuentas : Social.clases){
            usuarios.add(Cuentas.getUsername());
        }
        Usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(usuarios.toArray()));
    }
    
    private void setPosts(){
        post.clear();
        for (int loop = 0; loop < Social.clases.get(Usuarios.getSelectedIndex()).Posts.size(); loop++){
            post.add(Social.clases.get(Usuarios.getSelectedIndex()).Posts.get(loop));
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Posts;
    private javax.swing.JComboBox Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
