/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import Logica.UberSocial;
import static Swing.Log_In.userLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Post extends javax.swing.JFrame {
    UberSocial Social;
    /**
     * Creates new form Post
     */
    public Post(UberSocial Social) {
        initComponents();
        this.Social=Social;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarPost = new javax.swing.JButton();
        agregarAmigo = new javax.swing.JButton();
        agregarComment = new javax.swing.JButton();
        profileFrom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarPost.setText("Agregar Post");
        agregarPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPostActionPerformed(evt);
            }
        });

        agregarAmigo.setText("Agregar Amigo");
        agregarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAmigoActionPerformed(evt);
            }
        });

        agregarComment.setText("Agregar Commentario");
        agregarComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCommentActionPerformed(evt);
            }
        });

        profileFrom.setText("Perfil de");
        profileFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileFromActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileFrom)
                            .addComponent(agregarComment)
                            .addComponent(agregarAmigo)
                            .addComponent(agregarPost))
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(agregarPost)
                .addGap(31, 31, 31)
                .addComponent(agregarAmigo)
                .addGap(29, 29, 29)
                .addComponent(agregarComment)
                .addGap(42, 42, 42)
                .addComponent(profileFrom)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPostActionPerformed
        // TODO add your handling code here:
        try{
            String postCrear=JOptionPane.showInputDialog("Post: ");
            Social.AgregarPost(userLogin, postCrear);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_agregarPostActionPerformed

    private void agregarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAmigoActionPerformed
        // TODO add your handling code here:
        try{
            String userCrear=JOptionPane.showInputDialog("Amigo a crear: ");
            if(userCrear.equals(userLogin)){
                JOptionPane.showMessageDialog(null, "No podes agregarte a ti mismo");
            }else{
                if(Social.AgregarAmigo(userLogin, userCrear)){
                JOptionPane.showMessageDialog(null, "Se agrego amigo con exito.");
                }else{
                    JOptionPane.showMessageDialog(null, "No se agrego amigo con exito.");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_agregarAmigoActionPerformed

    private void agregarCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCommentActionPerformed
        new comment(Social).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarCommentActionPerformed

    private void profileFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileFromActionPerformed
        // TODO add your handling code here:
        try{
            String user = JOptionPane.showInputDialog("Ingrese el nombre de usuario:");
            Social.profileFrom(user);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_profileFromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Log_In(Social).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAmigo;
    private javax.swing.JButton agregarComment;
    private javax.swing.JButton agregarPost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton profileFrom;
    // End of variables declaration//GEN-END:variables
}
